apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-workflows
    targetRevision: 0.41.3  # 🔸 Verifique a versão mais recente no GitHub
    helm:
      releaseName: argo-workflows
      values: |
        server:
          ingress:
            enabled: true
            hostname: workflows.yourdomain.com
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
