apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook-source
  namespace: argocd
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    example:
      endpoint: /trigger
      method: POST
      port: 12000
      payload:
        example:
          value: "triggered"
