apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: example-sensor
  namespace: argocd
spec:
  dependencies:
    - name: example-dep
      eventSourceName: example-source
      eventName: example
  triggers:
    - template:
        name: example-trigger
        k8s:
          group: ""
          version: "v1"
          resource: "pods"
          operation: "create"
          source:
            resource:
              apiVersion: v1
              kind: Pod
              metadata:
                generateName: "example-trigger-pod-"
              spec:
                containers:
                  - name: example
                    image: busybox
                    command: ["/bin/sh", "-c", "echo Hello from Argo Events Sensor! && sleep 3600"]
