apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-sensor
  namespace: argocd
spec:
  dependencies:
    - name: webhook-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: argo-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1
              kind: Workflow
              metadata:
                generateName: hello-world-
                namespace: argocd
              spec:
                entrypoint: whalesay
                templates:
                  - name: whalesay
                    container:
                      image: docker/whalesay
                      command: ["cowsay"]
                      args: ["Hello World from Argo Events!"]
